name: CppCheck

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup CMake
      uses: lukka/run-cmake@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y 
        sudo apt-get install -y cppcheck

    - name: Run CppCheck
      ##run: cppcheck --enable=all --xml --xml-version=2 --check-config --std=c++11 .
      run: cppcheck --enable=all --force --inconclusive --xml --xml-version=2 --output-file=cppcheck-report.xml .
      

    - name: Set Artifact Name
      id: set_artifact_name
      run: |
          SHORT_SHA=$(echo "${GITHUB_SHA::5}")
          echo "ARTIFACT_NAME=cppcheck-report-$(date +'%Y-%m-%d-%H-%M-%S')-${SHORT_SHA}" >> $GITHUB_ENV
      shell: bash

    - name: Upload CppCheck results
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./cppcheck-report.xml
